### ISSUE TITLE
no default for gap_allowed & error in filtering columns

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateSpells#7]
I created a version 14 in the dev branch where gap_allowed is set to 1, since this looks compatibility with the older versions: is this correct?

However, version 14 still gives an error in the ACCESS script, can you check it out?

**Comment by DavideMessinaARS** [comment]
Fixed both the problems in https://github.com/ARS-toscana/CreateSpells/commit/434d8a143aa2fde6ff206bb383370ba4c878e6e5
